INSERT INTO TODOS (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1001, 'khan', 'Learn AWS', CURRENT_DATE(), FALSE);

INSERT INTO TODOS (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1002, 'khan', 'Learn Cloud', CURRENT_DATE(), FALSE);

INSERT INTO TODOS (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1003, 'khan', 'Learn Hacking', CURRENT_DATE(), FALSE);